WebPart for sending streams
SuaveIO/suave pull request #765
Opened 2023-01-14 10:12 UTC by njlr

- Add a WebPart for sending streams (`okStream`)
 - Add an example of sending a stream

2023-01-14 14:27 UTC, ademar commented
Hi, thanks for the PR. 
 
I think for the feature to be completed it should correctly handle the case where the length of the stream is unknown.
In that case it we should transmit the stream down the pipe using chunked transfer encoding.

If you handle that case and add some unit tests we can merge your work.

Thanks,

2023-01-14 22:42 UTC, njlr commented
> Hi, thanks for the PR.
> 
> I think for the feature to be completed it should correctly handle the case where the length of the stream is unknown. In that case it we should transmit the stream down the pipe using chunked transfer encoding.
> 
> If you handle that case and add some unit tests we can merge your work.
> 
> Thanks,

Great!

I have added a chunked variant and also some tests. Please let me know what you think 👍

2023-01-15 16:06 UTC, ademar requested changes
Hi, I've made some suggestions that I think make sense. Let me know what you think.

2023-01-15 16:06 UTC, ademar commented on src/Suave/Stream.fs
> +let okStreamChunked (makeStream : Async<Stream>) : WebPart =
Same here, use `Stream` rather than `Async<Stream>`

2023-01-15 16:06 UTC, ademar commented on src/Suave/Stream.fs
> +          do! transferStreamChunked conn stream
Shouldn't we send a newline here before sending the stream ?

2023-01-15 16:51 UTC, njlr commented on src/Suave/Stream.fs
> +let okStream (makeStream : Async<Stream>) : WebPart =
The reason I did it this way is to address a few things:

 1. The exact stream we need may only be known after inspecting the request and calling another service. For example, imagine we look into the request to get the user ID and then hit another service to fetch their profile picture. This process will likely be `Async`.
 
 2. Usually, we want to dispose of a stream when we are finished with it. I couldn't come up with a design that triggers disposal correctly without giving each invocation of the `WebPart` ownership of the stream
 
 3. Most streams do not allow multiple concurrent users, and giving the `WebPart` a mechanism for requesting a new stream instance side-steps many problems related to this

2023-01-15 17:44 UTC, ademar commented on src/Suave/Stream.fs
> +let okStream (makeStream : Async<Stream>) : WebPart =
OK, let's keep it like this.

2023-01-16 21:29 UTC, njlr commented
> Hi, I've made some suggestions that I think make sense. Let me know what you think.

I have pushed the suggested changes.

2023-01-17 04:39 UTC, ademar approved these changes

2023-01-17 04:39 UTC, merged

2023-01-17 04:40 UTC, ademar commented
Thank you very much!